package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesSubjects generated by hbm2java
 */
public class ArticlesSubjects implements java.io.Serializable {

	private Integer newid;
	private int id;
	private String subject;

	public ArticlesSubjects() {
	}

	public ArticlesSubjects(int id) {
		this.id = id;
	}

	public ArticlesSubjects(int id, String subject) {
		this.id = id;
		this.subject = subject;
	}

	public Integer getNewid() {
		return this.newid;
	}

	public void setNewid(Integer newid) {
		this.newid = newid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

}
