package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesRefsId generated by hbm2java
 */
public class ArticlesRefsId implements java.io.Serializable {

	private int id;
	private String firstAuthor;
	private Integer year;
	private String journal;
	private String volume;
	private String page;

	public ArticlesRefsId() {
	}

	public ArticlesRefsId(int id) {
		this.id = id;
	}

	public ArticlesRefsId(int id, String firstAuthor, Integer year,
			String journal, String volume, String page) {
		this.id = id;
		this.firstAuthor = firstAuthor;
		this.year = year;
		this.journal = journal;
		this.volume = volume;
		this.page = page;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstAuthor() {
		return this.firstAuthor;
	}

	public void setFirstAuthor(String firstAuthor) {
		this.firstAuthor = firstAuthor;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticlesRefsId))
			return false;
		ArticlesRefsId castOther = (ArticlesRefsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getFirstAuthor() == castOther.getFirstAuthor()) || (this
						.getFirstAuthor() != null
						&& castOther.getFirstAuthor() != null && this
						.getFirstAuthor().equals(castOther.getFirstAuthor())))
				&& ((this.getYear() == castOther.getYear()) || (this.getYear() != null
						&& castOther.getYear() != null && this.getYear()
						.equals(castOther.getYear())))
				&& ((this.getJournal() == castOther.getJournal()) || (this
						.getJournal() != null && castOther.getJournal() != null && this
						.getJournal().equals(castOther.getJournal())))
				&& ((this.getVolume() == castOther.getVolume()) || (this
						.getVolume() != null && castOther.getVolume() != null && this
						.getVolume().equals(castOther.getVolume())))
				&& ((this.getPage() == castOther.getPage()) || (this.getPage() != null
						&& castOther.getPage() != null && this.getPage()
						.equals(castOther.getPage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getFirstAuthor() == null ? 0 : this.getFirstAuthor()
						.hashCode());
		result = 37 * result
				+ (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result
				+ (getJournal() == null ? 0 : this.getJournal().hashCode());
		result = 37 * result
				+ (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37 * result
				+ (getPage() == null ? 0 : this.getPage().hashCode());
		return result;
	}

}
