package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesAdresses generated by hbm2java
 */
public class ArticlesAdresses implements java.io.Serializable {

	private ArticlesAdressesId id;

	public ArticlesAdresses() {
	}

	public ArticlesAdresses(ArticlesAdressesId id) {
		this.id = id;
	}

	public ArticlesAdressesId getId() {
		return this.id;
	}

	public void setId(ArticlesAdressesId id) {
		this.id = id;
	}

}
