package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesCountries generated by hbm2java
 */
public class ArticlesCountries implements java.io.Serializable {

	private ArticlesCountriesId id;

	public ArticlesCountries() {
	}

	public ArticlesCountries(ArticlesCountriesId id) {
		this.id = id;
	}

	public ArticlesCountriesId getId() {
		return this.id;
	}

	public void setId(ArticlesCountriesId id) {
		this.id = id;
	}

}
