package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesKeywordsId generated by hbm2java
 */
public class ArticlesKeywordsId implements java.io.Serializable {

	private int id;
	private String typeKeyw;
	private String keyword;

	public ArticlesKeywordsId() {
	}

	public ArticlesKeywordsId(int id) {
		this.id = id;
	}

	public ArticlesKeywordsId(int id, String typeKeyw, String keyword) {
		this.id = id;
		this.typeKeyw = typeKeyw;
		this.keyword = keyword;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTypeKeyw() {
		return this.typeKeyw;
	}

	public void setTypeKeyw(String typeKeyw) {
		this.typeKeyw = typeKeyw;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticlesKeywordsId))
			return false;
		ArticlesKeywordsId castOther = (ArticlesKeywordsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTypeKeyw() == castOther.getTypeKeyw()) || (this
						.getTypeKeyw() != null
						&& castOther.getTypeKeyw() != null && this
						.getTypeKeyw().equals(castOther.getTypeKeyw())))
				&& ((this.getKeyword() == castOther.getKeyword()) || (this
						.getKeyword() != null && castOther.getKeyword() != null && this
						.getKeyword().equals(castOther.getKeyword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getTypeKeyw() == null ? 0 : this.getTypeKeyw().hashCode());
		result = 37 * result
				+ (getKeyword() == null ? 0 : this.getKeyword().hashCode());
		return result;
	}

}
