package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesKeywords generated by hbm2java
 */
public class ArticlesKeywords implements java.io.Serializable {

	private ArticlesKeywordsId id;

	public ArticlesKeywords() {
	}

	public ArticlesKeywords(ArticlesKeywordsId id) {
		this.id = id;
	}

	public ArticlesKeywordsId getId() {
		return this.id;
	}

	public void setId(ArticlesKeywordsId id) {
		this.id = id;
	}

}
