package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesRefs generated by hbm2java
 */
public class ArticlesRefs implements java.io.Serializable {

	private ArticlesRefsId id;

	public ArticlesRefs() {
	}

	public ArticlesRefs(ArticlesRefsId id) {
		this.id = id;
	}

	public ArticlesRefsId getId() {
		return this.id;
	}

	public void setId(ArticlesRefsId id) {
		this.id = id;
	}

}
