package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesCountriesId generated by hbm2java
 */
public class ArticlesCountriesId implements java.io.Serializable {

	private int id;
	private int d1;
	private String country;

	public ArticlesCountriesId() {
	}

	public ArticlesCountriesId(int id, int d1) {
		this.id = id;
		this.d1 = d1;
	}

	public ArticlesCountriesId(int id, int d1, String country) {
		this.id = id;
		this.d1 = d1;
		this.country = country;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getD1() {
		return this.d1;
	}

	public void setD1(int d1) {
		this.d1 = d1;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticlesCountriesId))
			return false;
		ArticlesCountriesId castOther = (ArticlesCountriesId) other;

		return (this.getId() == castOther.getId())
				&& (this.getD1() == castOther.getD1())
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getD1();
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		return result;
	}

}
