package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesInstitutions generated by hbm2java
 */
public class ArticlesInstitutions implements java.io.Serializable {

	private Integer newid;
	private int id;
	private int d1;
	private int d2;
	private String institution;

	public ArticlesInstitutions() {
	}

	public ArticlesInstitutions(int id, int d1, int d2) {
		this.id = id;
		this.d1 = d1;
		this.d2 = d2;
	}

	public ArticlesInstitutions(int id, int d1, int d2, String institution) {
		this.id = id;
		this.d1 = d1;
		this.d2 = d2;
		this.institution = institution;
	}

	public Integer getNewid() {
		return this.newid;
	}

	public void setNewid(Integer newid) {
		this.newid = newid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getD1() {
		return this.d1;
	}

	public void setD1(int d1) {
		this.d1 = d1;
	}

	public int getD2() {
		return this.d2;
	}

	public void setD2(int d2) {
		this.d2 = d2;
	}

	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

}
