package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArticlesAuthors generated by hbm2java
 */
public class ArticlesAuthors implements java.io.Serializable {

	private Integer newid;
	private Integer id;
	private int d;
	private String author;
	private String lastname;

	public ArticlesAuthors() {
	}

	public ArticlesAuthors(int d) {
		this.d = d;
	}

	public ArticlesAuthors(Integer id, int d, String author, String lastname) {
		this.id = id;
		this.d = d;
		this.author = author;
		this.lastname = lastname;
	}

	public Integer getNewid() {
		return this.newid;
	}

	public void setNewid(Integer newid) {
		this.newid = newid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getD() {
		return this.d;
	}

	public void setD(int d) {
		this.d = d;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

}
