package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cleaninst generated by hbm2java
 */
public class Cleaninst implements java.io.Serializable {

	private Integer id;
	private Integer paper;
	private String nameOfInst;

	public Cleaninst() {
	}

	public Cleaninst(Integer paper, String nameOfInst) {
		this.paper = paper;
		this.nameOfInst = nameOfInst;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPaper() {
		return this.paper;
	}

	public void setPaper(Integer paper) {
		this.paper = paper;
	}

	public String getNameOfInst() {
		return this.nameOfInst;
	}

	public void setNameOfInst(String nameOfInst) {
		this.nameOfInst = nameOfInst;
	}

}
