package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cosinesim generated by hbm2java
 */
public class Cosinesim implements java.io.Serializable {

	private Integer id;
	private String name;
	private Double a1;
	private Double a2;
	private Double a3;
	private Double a4;
	private Double a5;
	private Double a6;
	private Double a7;
	private Double a8;
	private Double a9;
	private Double a10;
	private Double a11;
	private Double a12;
	private Double a13;
	private Double a14;
	private Double a15;
	private Double a16;
	private Double a17;
	private Double a18;
	private Double a19;
	private Double a20;
	private Double a21;
	private Double a22;
	private Double a23;
	private Double a24;
	private Double a25;
	private Double a26;
	private Double a27;
	private Double a28;
	private Double a29;
	private Double a30;
	private Double a31;
	private Double a32;
	private Double a33;
	private Double a34;
	private Double a35;
	private Double a36;
	private Double a37;
	private Double a38;
	private Double a39;
	private Double a40;
	private Double a41;
	private Double a42;
	private Double a43;
	private Double a44;
	private Double a45;
	private Double a46;
	private Double a47;
	private Double a48;
	private Double a49;
	private Double a50;
	private Double a51;
	private Double a52;
	private Double a53;
	private Double a54;
	private Double a55;
	private Double a56;
	private Double a57;
	private Double a58;
	private Double a59;
	private Double a60;
	private Double a61;
	private Double a62;
	private Double a63;
	private Double a64;
	private Double a65;
	private Double a66;
	private Double a67;
	private Double a68;
	private Double a69;
	private Double a70;
	private Double a71;
	private Double a72;
	private Double a73;
	private Double a74;
	private Double a75;
	private Double a76;
	private Double a77;
	private Double a78;
	private Double a79;
	private Double a80;
	private Double a81;
	private Double a82;
	private Double a83;
	private Double a84;
	private Double a85;
	private Double a86;
	private Double a87;
	private Double a88;
	private Double a89;
	private Double a90;
	private Double a91;
	private Double a92;
	private Double a93;
	private Double a94;
	private Double a95;
	private Double a96;
	private Double a97;
	private Double a98;
	private Double a99;
	private Double a100;
	private Double a101;
	private Double a102;
	private Double a103;
	private Double a104;
	private Double a105;
	private Double a106;
	private Double a107;
	private Double a108;
	private Double a109;
	private Double a110;
	private Double a111;
	private Double a112;
	private Double a113;
	private Double a114;
	private Double a115;
	private Double a116;
	private Double a117;
	private Double a118;
	private Double a119;
	private Double a120;
	private Double a121;
	private Double a122;
	private Double a123;
	private Double a124;
	private Double a125;
	private Double a126;
	private Double a127;
	private Double a128;
	private Double a129;
	private Double a130;
	private Double a131;
	private Double a132;
	private Double a133;
	private Double a134;
	private Double a135;
	private Double a136;
	private Double a137;
	private Double a138;
	private Double a139;
	private Double a140;
	private Double a141;
	private Double a142;
	private Double a143;
	private Double a144;
	private Double a145;
	private Double a146;
	private Double a147;
	private Double a148;
	private Double a149;
	private Double a150;
	private Double a151;
	private Double a152;
	private Double a153;
	private Double a154;
	private Double a155;
	private Double a156;
	private Double a157;
	private Double a158;
	private Double a159;
	private Double a160;
	private Double a161;
	private Double a162;
	private Double a163;
	private Double a164;
	private Double a165;
	private Double a166;
	private Double a167;
	private Double a168;
	private Double a169;
	private Double a170;
	private Double a171;
	private Double a172;
	private Double a173;
	private Double a174;
	private Double a175;
	private Double a176;
	private Double a177;
	private Double a178;
	private Double a179;
	private Double a180;
	private Double a181;
	private Double a182;
	private Double a183;
	private Double a184;
	private Double a185;
	private Double a186;
	private Double a187;
	private Double a188;
	private Double a189;
	private Double a190;
	private Double a191;
	private Double a192;
	private Double a193;
	private Double a194;
	private Double a195;
	private Double a196;
	private Double a197;
	private Double a198;
	private Double a199;
	private Double a200;
	private Double a201;
	private Double a202;
	private Double a203;
	private Double a204;
	private Double a205;
	private Double a206;
	private Double a207;
	private Double a208;
	private Double a209;
	private Double a210;
	private Double a211;
	private Double a212;
	private Double a213;
	private Double a214;
	private Double a215;
	private Double a216;
	private Double a217;
	private Double a218;
	private Double a219;
	private Double a220;
	private Double a221;
	private Double a222;

	public Cosinesim() {
	}

	public Cosinesim(String name, Double a1, Double a2, Double a3, Double a4,
			Double a5, Double a6, Double a7, Double a8, Double a9, Double a10,
			Double a11, Double a12, Double a13, Double a14, Double a15,
			Double a16, Double a17, Double a18, Double a19, Double a20,
			Double a21, Double a22, Double a23, Double a24, Double a25,
			Double a26, Double a27, Double a28, Double a29, Double a30,
			Double a31, Double a32, Double a33, Double a34, Double a35,
			Double a36, Double a37, Double a38, Double a39, Double a40,
			Double a41, Double a42, Double a43, Double a44, Double a45,
			Double a46, Double a47, Double a48, Double a49, Double a50,
			Double a51, Double a52, Double a53, Double a54, Double a55,
			Double a56, Double a57, Double a58, Double a59, Double a60,
			Double a61, Double a62, Double a63, Double a64, Double a65,
			Double a66, Double a67, Double a68, Double a69, Double a70,
			Double a71, Double a72, Double a73, Double a74, Double a75,
			Double a76, Double a77, Double a78, Double a79, Double a80,
			Double a81, Double a82, Double a83, Double a84, Double a85,
			Double a86, Double a87, Double a88, Double a89, Double a90,
			Double a91, Double a92, Double a93, Double a94, Double a95,
			Double a96, Double a97, Double a98, Double a99, Double a100,
			Double a101, Double a102, Double a103, Double a104, Double a105,
			Double a106, Double a107, Double a108, Double a109, Double a110,
			Double a111, Double a112, Double a113, Double a114, Double a115,
			Double a116, Double a117, Double a118, Double a119, Double a120,
			Double a121, Double a122, Double a123, Double a124, Double a125,
			Double a126, Double a127, Double a128, Double a129, Double a130,
			Double a131, Double a132, Double a133, Double a134, Double a135,
			Double a136, Double a137, Double a138, Double a139, Double a140,
			Double a141, Double a142, Double a143, Double a144, Double a145,
			Double a146, Double a147, Double a148, Double a149, Double a150,
			Double a151, Double a152, Double a153, Double a154, Double a155,
			Double a156, Double a157, Double a158, Double a159, Double a160,
			Double a161, Double a162, Double a163, Double a164, Double a165,
			Double a166, Double a167, Double a168, Double a169, Double a170,
			Double a171, Double a172, Double a173, Double a174, Double a175,
			Double a176, Double a177, Double a178, Double a179, Double a180,
			Double a181, Double a182, Double a183, Double a184, Double a185,
			Double a186, Double a187, Double a188, Double a189, Double a190,
			Double a191, Double a192, Double a193, Double a194, Double a195,
			Double a196, Double a197, Double a198, Double a199, Double a200,
			Double a201, Double a202, Double a203, Double a204, Double a205,
			Double a206, Double a207, Double a208, Double a209, Double a210,
			Double a211, Double a212, Double a213, Double a214, Double a215,
			Double a216, Double a217, Double a218, Double a219, Double a220,
			Double a221, Double a222) {
		this.name = name;
		this.a1 = a1;
		this.a2 = a2;
		this.a3 = a3;
		this.a4 = a4;
		this.a5 = a5;
		this.a6 = a6;
		this.a7 = a7;
		this.a8 = a8;
		this.a9 = a9;
		this.a10 = a10;
		this.a11 = a11;
		this.a12 = a12;
		this.a13 = a13;
		this.a14 = a14;
		this.a15 = a15;
		this.a16 = a16;
		this.a17 = a17;
		this.a18 = a18;
		this.a19 = a19;
		this.a20 = a20;
		this.a21 = a21;
		this.a22 = a22;
		this.a23 = a23;
		this.a24 = a24;
		this.a25 = a25;
		this.a26 = a26;
		this.a27 = a27;
		this.a28 = a28;
		this.a29 = a29;
		this.a30 = a30;
		this.a31 = a31;
		this.a32 = a32;
		this.a33 = a33;
		this.a34 = a34;
		this.a35 = a35;
		this.a36 = a36;
		this.a37 = a37;
		this.a38 = a38;
		this.a39 = a39;
		this.a40 = a40;
		this.a41 = a41;
		this.a42 = a42;
		this.a43 = a43;
		this.a44 = a44;
		this.a45 = a45;
		this.a46 = a46;
		this.a47 = a47;
		this.a48 = a48;
		this.a49 = a49;
		this.a50 = a50;
		this.a51 = a51;
		this.a52 = a52;
		this.a53 = a53;
		this.a54 = a54;
		this.a55 = a55;
		this.a56 = a56;
		this.a57 = a57;
		this.a58 = a58;
		this.a59 = a59;
		this.a60 = a60;
		this.a61 = a61;
		this.a62 = a62;
		this.a63 = a63;
		this.a64 = a64;
		this.a65 = a65;
		this.a66 = a66;
		this.a67 = a67;
		this.a68 = a68;
		this.a69 = a69;
		this.a70 = a70;
		this.a71 = a71;
		this.a72 = a72;
		this.a73 = a73;
		this.a74 = a74;
		this.a75 = a75;
		this.a76 = a76;
		this.a77 = a77;
		this.a78 = a78;
		this.a79 = a79;
		this.a80 = a80;
		this.a81 = a81;
		this.a82 = a82;
		this.a83 = a83;
		this.a84 = a84;
		this.a85 = a85;
		this.a86 = a86;
		this.a87 = a87;
		this.a88 = a88;
		this.a89 = a89;
		this.a90 = a90;
		this.a91 = a91;
		this.a92 = a92;
		this.a93 = a93;
		this.a94 = a94;
		this.a95 = a95;
		this.a96 = a96;
		this.a97 = a97;
		this.a98 = a98;
		this.a99 = a99;
		this.a100 = a100;
		this.a101 = a101;
		this.a102 = a102;
		this.a103 = a103;
		this.a104 = a104;
		this.a105 = a105;
		this.a106 = a106;
		this.a107 = a107;
		this.a108 = a108;
		this.a109 = a109;
		this.a110 = a110;
		this.a111 = a111;
		this.a112 = a112;
		this.a113 = a113;
		this.a114 = a114;
		this.a115 = a115;
		this.a116 = a116;
		this.a117 = a117;
		this.a118 = a118;
		this.a119 = a119;
		this.a120 = a120;
		this.a121 = a121;
		this.a122 = a122;
		this.a123 = a123;
		this.a124 = a124;
		this.a125 = a125;
		this.a126 = a126;
		this.a127 = a127;
		this.a128 = a128;
		this.a129 = a129;
		this.a130 = a130;
		this.a131 = a131;
		this.a132 = a132;
		this.a133 = a133;
		this.a134 = a134;
		this.a135 = a135;
		this.a136 = a136;
		this.a137 = a137;
		this.a138 = a138;
		this.a139 = a139;
		this.a140 = a140;
		this.a141 = a141;
		this.a142 = a142;
		this.a143 = a143;
		this.a144 = a144;
		this.a145 = a145;
		this.a146 = a146;
		this.a147 = a147;
		this.a148 = a148;
		this.a149 = a149;
		this.a150 = a150;
		this.a151 = a151;
		this.a152 = a152;
		this.a153 = a153;
		this.a154 = a154;
		this.a155 = a155;
		this.a156 = a156;
		this.a157 = a157;
		this.a158 = a158;
		this.a159 = a159;
		this.a160 = a160;
		this.a161 = a161;
		this.a162 = a162;
		this.a163 = a163;
		this.a164 = a164;
		this.a165 = a165;
		this.a166 = a166;
		this.a167 = a167;
		this.a168 = a168;
		this.a169 = a169;
		this.a170 = a170;
		this.a171 = a171;
		this.a172 = a172;
		this.a173 = a173;
		this.a174 = a174;
		this.a175 = a175;
		this.a176 = a176;
		this.a177 = a177;
		this.a178 = a178;
		this.a179 = a179;
		this.a180 = a180;
		this.a181 = a181;
		this.a182 = a182;
		this.a183 = a183;
		this.a184 = a184;
		this.a185 = a185;
		this.a186 = a186;
		this.a187 = a187;
		this.a188 = a188;
		this.a189 = a189;
		this.a190 = a190;
		this.a191 = a191;
		this.a192 = a192;
		this.a193 = a193;
		this.a194 = a194;
		this.a195 = a195;
		this.a196 = a196;
		this.a197 = a197;
		this.a198 = a198;
		this.a199 = a199;
		this.a200 = a200;
		this.a201 = a201;
		this.a202 = a202;
		this.a203 = a203;
		this.a204 = a204;
		this.a205 = a205;
		this.a206 = a206;
		this.a207 = a207;
		this.a208 = a208;
		this.a209 = a209;
		this.a210 = a210;
		this.a211 = a211;
		this.a212 = a212;
		this.a213 = a213;
		this.a214 = a214;
		this.a215 = a215;
		this.a216 = a216;
		this.a217 = a217;
		this.a218 = a218;
		this.a219 = a219;
		this.a220 = a220;
		this.a221 = a221;
		this.a222 = a222;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getA1() {
		return this.a1;
	}

	public void setA1(Double a1) {
		this.a1 = a1;
	}

	public Double getA2() {
		return this.a2;
	}

	public void setA2(Double a2) {
		this.a2 = a2;
	}

	public Double getA3() {
		return this.a3;
	}

	public void setA3(Double a3) {
		this.a3 = a3;
	}

	public Double getA4() {
		return this.a4;
	}

	public void setA4(Double a4) {
		this.a4 = a4;
	}

	public Double getA5() {
		return this.a5;
	}

	public void setA5(Double a5) {
		this.a5 = a5;
	}

	public Double getA6() {
		return this.a6;
	}

	public void setA6(Double a6) {
		this.a6 = a6;
	}

	public Double getA7() {
		return this.a7;
	}

	public void setA7(Double a7) {
		this.a7 = a7;
	}

	public Double getA8() {
		return this.a8;
	}

	public void setA8(Double a8) {
		this.a8 = a8;
	}

	public Double getA9() {
		return this.a9;
	}

	public void setA9(Double a9) {
		this.a9 = a9;
	}

	public Double getA10() {
		return this.a10;
	}

	public void setA10(Double a10) {
		this.a10 = a10;
	}

	public Double getA11() {
		return this.a11;
	}

	public void setA11(Double a11) {
		this.a11 = a11;
	}

	public Double getA12() {
		return this.a12;
	}

	public void setA12(Double a12) {
		this.a12 = a12;
	}

	public Double getA13() {
		return this.a13;
	}

	public void setA13(Double a13) {
		this.a13 = a13;
	}

	public Double getA14() {
		return this.a14;
	}

	public void setA14(Double a14) {
		this.a14 = a14;
	}

	public Double getA15() {
		return this.a15;
	}

	public void setA15(Double a15) {
		this.a15 = a15;
	}

	public Double getA16() {
		return this.a16;
	}

	public void setA16(Double a16) {
		this.a16 = a16;
	}

	public Double getA17() {
		return this.a17;
	}

	public void setA17(Double a17) {
		this.a17 = a17;
	}

	public Double getA18() {
		return this.a18;
	}

	public void setA18(Double a18) {
		this.a18 = a18;
	}

	public Double getA19() {
		return this.a19;
	}

	public void setA19(Double a19) {
		this.a19 = a19;
	}

	public Double getA20() {
		return this.a20;
	}

	public void setA20(Double a20) {
		this.a20 = a20;
	}

	public Double getA21() {
		return this.a21;
	}

	public void setA21(Double a21) {
		this.a21 = a21;
	}

	public Double getA22() {
		return this.a22;
	}

	public void setA22(Double a22) {
		this.a22 = a22;
	}

	public Double getA23() {
		return this.a23;
	}

	public void setA23(Double a23) {
		this.a23 = a23;
	}

	public Double getA24() {
		return this.a24;
	}

	public void setA24(Double a24) {
		this.a24 = a24;
	}

	public Double getA25() {
		return this.a25;
	}

	public void setA25(Double a25) {
		this.a25 = a25;
	}

	public Double getA26() {
		return this.a26;
	}

	public void setA26(Double a26) {
		this.a26 = a26;
	}

	public Double getA27() {
		return this.a27;
	}

	public void setA27(Double a27) {
		this.a27 = a27;
	}

	public Double getA28() {
		return this.a28;
	}

	public void setA28(Double a28) {
		this.a28 = a28;
	}

	public Double getA29() {
		return this.a29;
	}

	public void setA29(Double a29) {
		this.a29 = a29;
	}

	public Double getA30() {
		return this.a30;
	}

	public void setA30(Double a30) {
		this.a30 = a30;
	}

	public Double getA31() {
		return this.a31;
	}

	public void setA31(Double a31) {
		this.a31 = a31;
	}

	public Double getA32() {
		return this.a32;
	}

	public void setA32(Double a32) {
		this.a32 = a32;
	}

	public Double getA33() {
		return this.a33;
	}

	public void setA33(Double a33) {
		this.a33 = a33;
	}

	public Double getA34() {
		return this.a34;
	}

	public void setA34(Double a34) {
		this.a34 = a34;
	}

	public Double getA35() {
		return this.a35;
	}

	public void setA35(Double a35) {
		this.a35 = a35;
	}

	public Double getA36() {
		return this.a36;
	}

	public void setA36(Double a36) {
		this.a36 = a36;
	}

	public Double getA37() {
		return this.a37;
	}

	public void setA37(Double a37) {
		this.a37 = a37;
	}

	public Double getA38() {
		return this.a38;
	}

	public void setA38(Double a38) {
		this.a38 = a38;
	}

	public Double getA39() {
		return this.a39;
	}

	public void setA39(Double a39) {
		this.a39 = a39;
	}

	public Double getA40() {
		return this.a40;
	}

	public void setA40(Double a40) {
		this.a40 = a40;
	}

	public Double getA41() {
		return this.a41;
	}

	public void setA41(Double a41) {
		this.a41 = a41;
	}

	public Double getA42() {
		return this.a42;
	}

	public void setA42(Double a42) {
		this.a42 = a42;
	}

	public Double getA43() {
		return this.a43;
	}

	public void setA43(Double a43) {
		this.a43 = a43;
	}

	public Double getA44() {
		return this.a44;
	}

	public void setA44(Double a44) {
		this.a44 = a44;
	}

	public Double getA45() {
		return this.a45;
	}

	public void setA45(Double a45) {
		this.a45 = a45;
	}

	public Double getA46() {
		return this.a46;
	}

	public void setA46(Double a46) {
		this.a46 = a46;
	}

	public Double getA47() {
		return this.a47;
	}

	public void setA47(Double a47) {
		this.a47 = a47;
	}

	public Double getA48() {
		return this.a48;
	}

	public void setA48(Double a48) {
		this.a48 = a48;
	}

	public Double getA49() {
		return this.a49;
	}

	public void setA49(Double a49) {
		this.a49 = a49;
	}

	public Double getA50() {
		return this.a50;
	}

	public void setA50(Double a50) {
		this.a50 = a50;
	}

	public Double getA51() {
		return this.a51;
	}

	public void setA51(Double a51) {
		this.a51 = a51;
	}

	public Double getA52() {
		return this.a52;
	}

	public void setA52(Double a52) {
		this.a52 = a52;
	}

	public Double getA53() {
		return this.a53;
	}

	public void setA53(Double a53) {
		this.a53 = a53;
	}

	public Double getA54() {
		return this.a54;
	}

	public void setA54(Double a54) {
		this.a54 = a54;
	}

	public Double getA55() {
		return this.a55;
	}

	public void setA55(Double a55) {
		this.a55 = a55;
	}

	public Double getA56() {
		return this.a56;
	}

	public void setA56(Double a56) {
		this.a56 = a56;
	}

	public Double getA57() {
		return this.a57;
	}

	public void setA57(Double a57) {
		this.a57 = a57;
	}

	public Double getA58() {
		return this.a58;
	}

	public void setA58(Double a58) {
		this.a58 = a58;
	}

	public Double getA59() {
		return this.a59;
	}

	public void setA59(Double a59) {
		this.a59 = a59;
	}

	public Double getA60() {
		return this.a60;
	}

	public void setA60(Double a60) {
		this.a60 = a60;
	}

	public Double getA61() {
		return this.a61;
	}

	public void setA61(Double a61) {
		this.a61 = a61;
	}

	public Double getA62() {
		return this.a62;
	}

	public void setA62(Double a62) {
		this.a62 = a62;
	}

	public Double getA63() {
		return this.a63;
	}

	public void setA63(Double a63) {
		this.a63 = a63;
	}

	public Double getA64() {
		return this.a64;
	}

	public void setA64(Double a64) {
		this.a64 = a64;
	}

	public Double getA65() {
		return this.a65;
	}

	public void setA65(Double a65) {
		this.a65 = a65;
	}

	public Double getA66() {
		return this.a66;
	}

	public void setA66(Double a66) {
		this.a66 = a66;
	}

	public Double getA67() {
		return this.a67;
	}

	public void setA67(Double a67) {
		this.a67 = a67;
	}

	public Double getA68() {
		return this.a68;
	}

	public void setA68(Double a68) {
		this.a68 = a68;
	}

	public Double getA69() {
		return this.a69;
	}

	public void setA69(Double a69) {
		this.a69 = a69;
	}

	public Double getA70() {
		return this.a70;
	}

	public void setA70(Double a70) {
		this.a70 = a70;
	}

	public Double getA71() {
		return this.a71;
	}

	public void setA71(Double a71) {
		this.a71 = a71;
	}

	public Double getA72() {
		return this.a72;
	}

	public void setA72(Double a72) {
		this.a72 = a72;
	}

	public Double getA73() {
		return this.a73;
	}

	public void setA73(Double a73) {
		this.a73 = a73;
	}

	public Double getA74() {
		return this.a74;
	}

	public void setA74(Double a74) {
		this.a74 = a74;
	}

	public Double getA75() {
		return this.a75;
	}

	public void setA75(Double a75) {
		this.a75 = a75;
	}

	public Double getA76() {
		return this.a76;
	}

	public void setA76(Double a76) {
		this.a76 = a76;
	}

	public Double getA77() {
		return this.a77;
	}

	public void setA77(Double a77) {
		this.a77 = a77;
	}

	public Double getA78() {
		return this.a78;
	}

	public void setA78(Double a78) {
		this.a78 = a78;
	}

	public Double getA79() {
		return this.a79;
	}

	public void setA79(Double a79) {
		this.a79 = a79;
	}

	public Double getA80() {
		return this.a80;
	}

	public void setA80(Double a80) {
		this.a80 = a80;
	}

	public Double getA81() {
		return this.a81;
	}

	public void setA81(Double a81) {
		this.a81 = a81;
	}

	public Double getA82() {
		return this.a82;
	}

	public void setA82(Double a82) {
		this.a82 = a82;
	}

	public Double getA83() {
		return this.a83;
	}

	public void setA83(Double a83) {
		this.a83 = a83;
	}

	public Double getA84() {
		return this.a84;
	}

	public void setA84(Double a84) {
		this.a84 = a84;
	}

	public Double getA85() {
		return this.a85;
	}

	public void setA85(Double a85) {
		this.a85 = a85;
	}

	public Double getA86() {
		return this.a86;
	}

	public void setA86(Double a86) {
		this.a86 = a86;
	}

	public Double getA87() {
		return this.a87;
	}

	public void setA87(Double a87) {
		this.a87 = a87;
	}

	public Double getA88() {
		return this.a88;
	}

	public void setA88(Double a88) {
		this.a88 = a88;
	}

	public Double getA89() {
		return this.a89;
	}

	public void setA89(Double a89) {
		this.a89 = a89;
	}

	public Double getA90() {
		return this.a90;
	}

	public void setA90(Double a90) {
		this.a90 = a90;
	}

	public Double getA91() {
		return this.a91;
	}

	public void setA91(Double a91) {
		this.a91 = a91;
	}

	public Double getA92() {
		return this.a92;
	}

	public void setA92(Double a92) {
		this.a92 = a92;
	}

	public Double getA93() {
		return this.a93;
	}

	public void setA93(Double a93) {
		this.a93 = a93;
	}

	public Double getA94() {
		return this.a94;
	}

	public void setA94(Double a94) {
		this.a94 = a94;
	}

	public Double getA95() {
		return this.a95;
	}

	public void setA95(Double a95) {
		this.a95 = a95;
	}

	public Double getA96() {
		return this.a96;
	}

	public void setA96(Double a96) {
		this.a96 = a96;
	}

	public Double getA97() {
		return this.a97;
	}

	public void setA97(Double a97) {
		this.a97 = a97;
	}

	public Double getA98() {
		return this.a98;
	}

	public void setA98(Double a98) {
		this.a98 = a98;
	}

	public Double getA99() {
		return this.a99;
	}

	public void setA99(Double a99) {
		this.a99 = a99;
	}

	public Double getA100() {
		return this.a100;
	}

	public void setA100(Double a100) {
		this.a100 = a100;
	}

	public Double getA101() {
		return this.a101;
	}

	public void setA101(Double a101) {
		this.a101 = a101;
	}

	public Double getA102() {
		return this.a102;
	}

	public void setA102(Double a102) {
		this.a102 = a102;
	}

	public Double getA103() {
		return this.a103;
	}

	public void setA103(Double a103) {
		this.a103 = a103;
	}

	public Double getA104() {
		return this.a104;
	}

	public void setA104(Double a104) {
		this.a104 = a104;
	}

	public Double getA105() {
		return this.a105;
	}

	public void setA105(Double a105) {
		this.a105 = a105;
	}

	public Double getA106() {
		return this.a106;
	}

	public void setA106(Double a106) {
		this.a106 = a106;
	}

	public Double getA107() {
		return this.a107;
	}

	public void setA107(Double a107) {
		this.a107 = a107;
	}

	public Double getA108() {
		return this.a108;
	}

	public void setA108(Double a108) {
		this.a108 = a108;
	}

	public Double getA109() {
		return this.a109;
	}

	public void setA109(Double a109) {
		this.a109 = a109;
	}

	public Double getA110() {
		return this.a110;
	}

	public void setA110(Double a110) {
		this.a110 = a110;
	}

	public Double getA111() {
		return this.a111;
	}

	public void setA111(Double a111) {
		this.a111 = a111;
	}

	public Double getA112() {
		return this.a112;
	}

	public void setA112(Double a112) {
		this.a112 = a112;
	}

	public Double getA113() {
		return this.a113;
	}

	public void setA113(Double a113) {
		this.a113 = a113;
	}

	public Double getA114() {
		return this.a114;
	}

	public void setA114(Double a114) {
		this.a114 = a114;
	}

	public Double getA115() {
		return this.a115;
	}

	public void setA115(Double a115) {
		this.a115 = a115;
	}

	public Double getA116() {
		return this.a116;
	}

	public void setA116(Double a116) {
		this.a116 = a116;
	}

	public Double getA117() {
		return this.a117;
	}

	public void setA117(Double a117) {
		this.a117 = a117;
	}

	public Double getA118() {
		return this.a118;
	}

	public void setA118(Double a118) {
		this.a118 = a118;
	}

	public Double getA119() {
		return this.a119;
	}

	public void setA119(Double a119) {
		this.a119 = a119;
	}

	public Double getA120() {
		return this.a120;
	}

	public void setA120(Double a120) {
		this.a120 = a120;
	}

	public Double getA121() {
		return this.a121;
	}

	public void setA121(Double a121) {
		this.a121 = a121;
	}

	public Double getA122() {
		return this.a122;
	}

	public void setA122(Double a122) {
		this.a122 = a122;
	}

	public Double getA123() {
		return this.a123;
	}

	public void setA123(Double a123) {
		this.a123 = a123;
	}

	public Double getA124() {
		return this.a124;
	}

	public void setA124(Double a124) {
		this.a124 = a124;
	}

	public Double getA125() {
		return this.a125;
	}

	public void setA125(Double a125) {
		this.a125 = a125;
	}

	public Double getA126() {
		return this.a126;
	}

	public void setA126(Double a126) {
		this.a126 = a126;
	}

	public Double getA127() {
		return this.a127;
	}

	public void setA127(Double a127) {
		this.a127 = a127;
	}

	public Double getA128() {
		return this.a128;
	}

	public void setA128(Double a128) {
		this.a128 = a128;
	}

	public Double getA129() {
		return this.a129;
	}

	public void setA129(Double a129) {
		this.a129 = a129;
	}

	public Double getA130() {
		return this.a130;
	}

	public void setA130(Double a130) {
		this.a130 = a130;
	}

	public Double getA131() {
		return this.a131;
	}

	public void setA131(Double a131) {
		this.a131 = a131;
	}

	public Double getA132() {
		return this.a132;
	}

	public void setA132(Double a132) {
		this.a132 = a132;
	}

	public Double getA133() {
		return this.a133;
	}

	public void setA133(Double a133) {
		this.a133 = a133;
	}

	public Double getA134() {
		return this.a134;
	}

	public void setA134(Double a134) {
		this.a134 = a134;
	}

	public Double getA135() {
		return this.a135;
	}

	public void setA135(Double a135) {
		this.a135 = a135;
	}

	public Double getA136() {
		return this.a136;
	}

	public void setA136(Double a136) {
		this.a136 = a136;
	}

	public Double getA137() {
		return this.a137;
	}

	public void setA137(Double a137) {
		this.a137 = a137;
	}

	public Double getA138() {
		return this.a138;
	}

	public void setA138(Double a138) {
		this.a138 = a138;
	}

	public Double getA139() {
		return this.a139;
	}

	public void setA139(Double a139) {
		this.a139 = a139;
	}

	public Double getA140() {
		return this.a140;
	}

	public void setA140(Double a140) {
		this.a140 = a140;
	}

	public Double getA141() {
		return this.a141;
	}

	public void setA141(Double a141) {
		this.a141 = a141;
	}

	public Double getA142() {
		return this.a142;
	}

	public void setA142(Double a142) {
		this.a142 = a142;
	}

	public Double getA143() {
		return this.a143;
	}

	public void setA143(Double a143) {
		this.a143 = a143;
	}

	public Double getA144() {
		return this.a144;
	}

	public void setA144(Double a144) {
		this.a144 = a144;
	}

	public Double getA145() {
		return this.a145;
	}

	public void setA145(Double a145) {
		this.a145 = a145;
	}

	public Double getA146() {
		return this.a146;
	}

	public void setA146(Double a146) {
		this.a146 = a146;
	}

	public Double getA147() {
		return this.a147;
	}

	public void setA147(Double a147) {
		this.a147 = a147;
	}

	public Double getA148() {
		return this.a148;
	}

	public void setA148(Double a148) {
		this.a148 = a148;
	}

	public Double getA149() {
		return this.a149;
	}

	public void setA149(Double a149) {
		this.a149 = a149;
	}

	public Double getA150() {
		return this.a150;
	}

	public void setA150(Double a150) {
		this.a150 = a150;
	}

	public Double getA151() {
		return this.a151;
	}

	public void setA151(Double a151) {
		this.a151 = a151;
	}

	public Double getA152() {
		return this.a152;
	}

	public void setA152(Double a152) {
		this.a152 = a152;
	}

	public Double getA153() {
		return this.a153;
	}

	public void setA153(Double a153) {
		this.a153 = a153;
	}

	public Double getA154() {
		return this.a154;
	}

	public void setA154(Double a154) {
		this.a154 = a154;
	}

	public Double getA155() {
		return this.a155;
	}

	public void setA155(Double a155) {
		this.a155 = a155;
	}

	public Double getA156() {
		return this.a156;
	}

	public void setA156(Double a156) {
		this.a156 = a156;
	}

	public Double getA157() {
		return this.a157;
	}

	public void setA157(Double a157) {
		this.a157 = a157;
	}

	public Double getA158() {
		return this.a158;
	}

	public void setA158(Double a158) {
		this.a158 = a158;
	}

	public Double getA159() {
		return this.a159;
	}

	public void setA159(Double a159) {
		this.a159 = a159;
	}

	public Double getA160() {
		return this.a160;
	}

	public void setA160(Double a160) {
		this.a160 = a160;
	}

	public Double getA161() {
		return this.a161;
	}

	public void setA161(Double a161) {
		this.a161 = a161;
	}

	public Double getA162() {
		return this.a162;
	}

	public void setA162(Double a162) {
		this.a162 = a162;
	}

	public Double getA163() {
		return this.a163;
	}

	public void setA163(Double a163) {
		this.a163 = a163;
	}

	public Double getA164() {
		return this.a164;
	}

	public void setA164(Double a164) {
		this.a164 = a164;
	}

	public Double getA165() {
		return this.a165;
	}

	public void setA165(Double a165) {
		this.a165 = a165;
	}

	public Double getA166() {
		return this.a166;
	}

	public void setA166(Double a166) {
		this.a166 = a166;
	}

	public Double getA167() {
		return this.a167;
	}

	public void setA167(Double a167) {
		this.a167 = a167;
	}

	public Double getA168() {
		return this.a168;
	}

	public void setA168(Double a168) {
		this.a168 = a168;
	}

	public Double getA169() {
		return this.a169;
	}

	public void setA169(Double a169) {
		this.a169 = a169;
	}

	public Double getA170() {
		return this.a170;
	}

	public void setA170(Double a170) {
		this.a170 = a170;
	}

	public Double getA171() {
		return this.a171;
	}

	public void setA171(Double a171) {
		this.a171 = a171;
	}

	public Double getA172() {
		return this.a172;
	}

	public void setA172(Double a172) {
		this.a172 = a172;
	}

	public Double getA173() {
		return this.a173;
	}

	public void setA173(Double a173) {
		this.a173 = a173;
	}

	public Double getA174() {
		return this.a174;
	}

	public void setA174(Double a174) {
		this.a174 = a174;
	}

	public Double getA175() {
		return this.a175;
	}

	public void setA175(Double a175) {
		this.a175 = a175;
	}

	public Double getA176() {
		return this.a176;
	}

	public void setA176(Double a176) {
		this.a176 = a176;
	}

	public Double getA177() {
		return this.a177;
	}

	public void setA177(Double a177) {
		this.a177 = a177;
	}

	public Double getA178() {
		return this.a178;
	}

	public void setA178(Double a178) {
		this.a178 = a178;
	}

	public Double getA179() {
		return this.a179;
	}

	public void setA179(Double a179) {
		this.a179 = a179;
	}

	public Double getA180() {
		return this.a180;
	}

	public void setA180(Double a180) {
		this.a180 = a180;
	}

	public Double getA181() {
		return this.a181;
	}

	public void setA181(Double a181) {
		this.a181 = a181;
	}

	public Double getA182() {
		return this.a182;
	}

	public void setA182(Double a182) {
		this.a182 = a182;
	}

	public Double getA183() {
		return this.a183;
	}

	public void setA183(Double a183) {
		this.a183 = a183;
	}

	public Double getA184() {
		return this.a184;
	}

	public void setA184(Double a184) {
		this.a184 = a184;
	}

	public Double getA185() {
		return this.a185;
	}

	public void setA185(Double a185) {
		this.a185 = a185;
	}

	public Double getA186() {
		return this.a186;
	}

	public void setA186(Double a186) {
		this.a186 = a186;
	}

	public Double getA187() {
		return this.a187;
	}

	public void setA187(Double a187) {
		this.a187 = a187;
	}

	public Double getA188() {
		return this.a188;
	}

	public void setA188(Double a188) {
		this.a188 = a188;
	}

	public Double getA189() {
		return this.a189;
	}

	public void setA189(Double a189) {
		this.a189 = a189;
	}

	public Double getA190() {
		return this.a190;
	}

	public void setA190(Double a190) {
		this.a190 = a190;
	}

	public Double getA191() {
		return this.a191;
	}

	public void setA191(Double a191) {
		this.a191 = a191;
	}

	public Double getA192() {
		return this.a192;
	}

	public void setA192(Double a192) {
		this.a192 = a192;
	}

	public Double getA193() {
		return this.a193;
	}

	public void setA193(Double a193) {
		this.a193 = a193;
	}

	public Double getA194() {
		return this.a194;
	}

	public void setA194(Double a194) {
		this.a194 = a194;
	}

	public Double getA195() {
		return this.a195;
	}

	public void setA195(Double a195) {
		this.a195 = a195;
	}

	public Double getA196() {
		return this.a196;
	}

	public void setA196(Double a196) {
		this.a196 = a196;
	}

	public Double getA197() {
		return this.a197;
	}

	public void setA197(Double a197) {
		this.a197 = a197;
	}

	public Double getA198() {
		return this.a198;
	}

	public void setA198(Double a198) {
		this.a198 = a198;
	}

	public Double getA199() {
		return this.a199;
	}

	public void setA199(Double a199) {
		this.a199 = a199;
	}

	public Double getA200() {
		return this.a200;
	}

	public void setA200(Double a200) {
		this.a200 = a200;
	}

	public Double getA201() {
		return this.a201;
	}

	public void setA201(Double a201) {
		this.a201 = a201;
	}

	public Double getA202() {
		return this.a202;
	}

	public void setA202(Double a202) {
		this.a202 = a202;
	}

	public Double getA203() {
		return this.a203;
	}

	public void setA203(Double a203) {
		this.a203 = a203;
	}

	public Double getA204() {
		return this.a204;
	}

	public void setA204(Double a204) {
		this.a204 = a204;
	}

	public Double getA205() {
		return this.a205;
	}

	public void setA205(Double a205) {
		this.a205 = a205;
	}

	public Double getA206() {
		return this.a206;
	}

	public void setA206(Double a206) {
		this.a206 = a206;
	}

	public Double getA207() {
		return this.a207;
	}

	public void setA207(Double a207) {
		this.a207 = a207;
	}

	public Double getA208() {
		return this.a208;
	}

	public void setA208(Double a208) {
		this.a208 = a208;
	}

	public Double getA209() {
		return this.a209;
	}

	public void setA209(Double a209) {
		this.a209 = a209;
	}

	public Double getA210() {
		return this.a210;
	}

	public void setA210(Double a210) {
		this.a210 = a210;
	}

	public Double getA211() {
		return this.a211;
	}

	public void setA211(Double a211) {
		this.a211 = a211;
	}

	public Double getA212() {
		return this.a212;
	}

	public void setA212(Double a212) {
		this.a212 = a212;
	}

	public Double getA213() {
		return this.a213;
	}

	public void setA213(Double a213) {
		this.a213 = a213;
	}

	public Double getA214() {
		return this.a214;
	}

	public void setA214(Double a214) {
		this.a214 = a214;
	}

	public Double getA215() {
		return this.a215;
	}

	public void setA215(Double a215) {
		this.a215 = a215;
	}

	public Double getA216() {
		return this.a216;
	}

	public void setA216(Double a216) {
		this.a216 = a216;
	}

	public Double getA217() {
		return this.a217;
	}

	public void setA217(Double a217) {
		this.a217 = a217;
	}

	public Double getA218() {
		return this.a218;
	}

	public void setA218(Double a218) {
		this.a218 = a218;
	}

	public Double getA219() {
		return this.a219;
	}

	public void setA219(Double a219) {
		this.a219 = a219;
	}

	public Double getA220() {
		return this.a220;
	}

	public void setA220(Double a220) {
		this.a220 = a220;
	}

	public Double getA221() {
		return this.a221;
	}

	public void setA221(Double a221) {
		this.a221 = a221;
	}

	public Double getA222() {
		return this.a222;
	}

	public void setA222(Double a222) {
		this.a222 = a222;
	}

}
