package project.dmkm.features.objects.DAO;

// Generated Jun 2, 2013 1:29:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * Matrix generated by hbm2java
 */
public class Matrix implements java.io.Serializable {

	private Integer id;
	private Integer paper1;
	private Integer paper2;
	private Float discplinedistance;
	private String author;

	public Matrix() {
	}

	public Matrix(Integer paper1, Integer paper2, Float discplinedistance,
			String author) {
		this.paper1 = paper1;
		this.paper2 = paper2;
		this.discplinedistance = discplinedistance;
		this.author = author;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPaper1() {
		return this.paper1;
	}

	public void setPaper1(Integer paper1) {
		this.paper1 = paper1;
	}

	public Integer getPaper2() {
		return this.paper2;
	}

	public void setPaper2(Integer paper2) {
		this.paper2 = paper2;
	}

	public Float getDiscplinedistance() {
		return this.discplinedistance;
	}

	public void setDiscplinedistance(Float discplinedistance) {
		this.discplinedistance = discplinedistance;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

}
