package project.dmkm.features.objects.DAO;

// Generated May 21, 2013 4:29:49 AM by Hibernate Tools 3.4.0.CR1

/**
 * Titre generated by hbm2java
 */
public class Titre implements java.io.Serializable {

	private String titre;

	public Titre() {
	}

	public Titre(String titre) {
		this.titre = titre;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

}
