package project.dmkm.stores;

public class CosimMatrix {
	
	public static String getColumnName(String a)
	{
		switch (a)
		{
				case"a1":	return	"ACOUSTICS";
			case"a2":	return	"AGRICULTURAL ECONOMICS & POLICY";
			case"a3":	return	"AGRICULTURAL ENGINEERING";
			case"a4":	return	"AGRICULTURE, DAIRY & ANIMAL SCIENCE";
			case"a5":	return	"AGRICULTURE, MULTIDISCIPLINARY";
			case"a6":	return	"AGRONOMY";
			case"a7":	return	"ALLERGY";
			case"a8":	return	"ANATOMY & MORPHOLOGY";
			case"a9":	return	"ANDROLOGY";
			case"a10":	return	"ANESTHESIOLOGY";
			case"a11":	return	"ANTHROPOLOGY";
			case"a12":	return	"AREA STUDIES";
			case"a13":	return	"ASTRONOMY & ASTROPHYSICS";
			case"a14":	return	"AUTOMATION & CONTROL SYSTEMS";
			case"a15":	return	"BEHAVIORAL SCIENCES";
			case"a16":	return	"BIOCHEMICAL RESEARCH METHODS";
			case"a17":	return	"BIOCHEMISTRY & MOLECULAR BIOLOGY";
			case"a18":	return	"BIODIVERSITY CONSERVATION";
			case"a19":	return	"BIOLOGY";
			case"a20":	return	"BIOPHYSICS";
			case"a21":	return	"BIOTECHNOLOGY & APPLIED MICROBIOLOGY";
			case"a22":	return	"BUSINESS";
			case"a23":	return	"BUSINESS, FINANCE";
			case"a24":	return	"CARDIAC & CARDIOVASCULAR SYSTEMS";
			case"a25":	return	"CELL & TISSUE ENGINEERING";
			case"a26":	return	"CELL BIOLOGY";
			case"a27":	return	"CHEMISTRY, ANALYTICAL";
			case"a28":	return	"CHEMISTRY, APPLIED";
			case"a29":	return	"CHEMISTRY, INORGANIC & NUCLEAR";
			case"a30":	return	"CHEMISTRY, MEDICINAL";
			case"a31":	return	"CHEMISTRY, MULTIDISCIPLINARY";
			case"a32":	return	"CHEMISTRY, ORGANIC";
			case"a33":	return	"CHEMISTRY, PHYSICAL";
			case"a34":	return	"CLINICAL NEUROLOGY";
			case"a35":	return	"COMMUNICATION";
			case"a36":	return	"COMPUTER SCIENCE, ARTIFICIAL INTELLIGENCE";
			case"a37":	return	"COMPUTER SCIENCE, CYBERNETICS";
			case"a38":	return	"COMPUTER SCIENCE, HARDWARE & ARCHITECTURE";
			case"a39":	return	"COMPUTER SCIENCE, INFORMATION SYSTEMS";
			case"a40":	return	"COMPUTER SCIENCE, INTERDISCIPLINARY APPLICATIONS";
			case"a41":	return	"COMPUTER SCIENCE, SOFTWARE ENGINEERING";
			case"a42":	return	"COMPUTER SCIENCE, THEORY & METHODS";
			case"a43":	return	"CONSTRUCTION & BUILDING TECHNOLOGY";
			case"a44":	return	"CRIMINOLOGY & PENOLOGY";
			case"a45":	return	"CRITICAL CARE MEDICINE";
			case"a46":	return	"CRYSTALLOGRAPHY";
			case"a47":	return	"DEMOGRAPHY";
			case"a48":	return	"DENTISTRY, ORAL SURGERY & MEDICINE";
			case"a49":	return	"DERMATOLOGY";
			case"a50":	return	"DEVELOPMENTAL BIOLOGY";
			case"a51":	return	"ECOLOGY";
			case"a52":	return	"ECONOMICS";
			case"a53":	return	"EDUCATION & EDUCATIONAL RESEARCH";
			case"a54":	return	"EDUCATION, SCIENTIFIC DISCIPLINES";
			case"a55":	return	"EDUCATION, SPECIAL";
			case"a56":	return	"ELECTROCHEMISTRY";
			case"a57":	return	"EMERGENCY MEDICINE";
			case"a58":	return	"ENDOCRINOLOGY & METABOLISM";
			case"a59":	return	"ENERGY & FUELS";
			case"a60":	return	"ENGINEERING, AEROSPACE";
			case"a61":	return	"ENGINEERING, BIOMEDICAL";
			case"a62":	return	"ENGINEERING, CHEMICAL";
			case"a63":	return	"ENGINEERING, CIVIL";
			case"a64":	return	"ENGINEERING, ELECTRICAL & ELECTRONIC";
			case"a65":	return	"ENGINEERING, ENVIRONMENTAL";
			case"a66":	return	"ENGINEERING, GEOLOGICAL";
			case"a67":	return	"ENGINEERING, INDUSTRIAL";
			case"a68":	return	"ENGINEERING, MANUFACTURING";
			case"a69":	return	"ENGINEERING, MARINE";
			case"a70":	return	"ENGINEERING, MECHANICAL";
			case"a71":	return	"ENGINEERING, MULTIDISCIPLINARY";
			case"a72":	return	"ENGINEERING, OCEAN";
			case"a73":	return	"ENGINEERING, PETROLEUM";
			case"a74":	return	"ENTOMOLOGY";
			case"a75":	return	"ENVIRONMENTAL SCIENCES";
			case"a76":	return	"ENVIRONMENTAL STUDIES";
			case"a77":	return	"ERGONOMICS";
			case"a78":	return	"ETHICS";
			case"a79":	return	"ETHNIC STUDIES";
			case"a80":	return	"EVOLUTIONARY BIOLOGY";
			case"a81":	return	"FAMILY STUDIES";
			case"a82":	return	"FISHERIES";
			case"a83":	return	"FOOD SCIENCE & TECHNOLOGY";
			case"a84":	return	"FORESTRY";
			case"a85":	return	"GASTROENTEROLOGY & HEPATOLOGY";
			case"a86":	return	"GENETICS & HEREDITY";
			case"a87":	return	"GEOCHEMISTRY & GEOPHYSICS";
			case"a88":	return	"GEOGRAPHY";
			case"a89":	return	"GEOGRAPHY, PHYSICAL";
			case"a90":	return	"GEOLOGY";
			case"a91":	return	"GEOSCIENCES, MULTIDISCIPLINARY";
			case"a92":	return	"GERIATRICS & GERONTOLOGY";
			case"a93":	return	"GERONTOLOGY";
			case"a94":	return	"HEALTH CARE SCIENCES & SERVICES";
			case"a95":	return	"HEALTH POLICY & SERVICES";
			case"a96":	return	"HEMATOLOGY";
			case"a97":	return	"HISTORY";
			case"a98":	return	"HISTORY & PHILOSOPHY OF SCIENCE";
			case"a99":	return	"HISTORY OF SOCIAL SCIENCES";
			case"a100":	return	"HORTICULTURE";
			case"a101":	return	"HOSPITALITY, LEISURE, SPORT & TOURISM";
			case"a102":	return	"IMAGING SCIENCE & PHOTOGRAPHIC TECHNOLOGY";
			case"a103":	return	"IMMUNOLOGY";
			case"a104":	return	"INDUSTRIAL RELATIONS & LABOR";
			case"a105":	return	"INFECTIOUS DISEASES";
			case"a106":	return	"INFORMATION SCIENCE & LIBRARY SCIENCE";
			case"a107":	return	"INSTRUMENTS & INSTRUMENTATION";
			case"a108":	return	"INTEGRATIVE & COMPLEMENTARY MEDICINE";
			case"a109":	return	"INTERNATIONAL RELATIONS";
			case"a110":	return	"LAW";
			case"a111":	return	"LIMNOLOGY";
			case"a112":	return	"LINGUISTICS";
			case"a113":	return	"MANAGEMENT";
			case"a114":	return	"MARINE & FRESHWATER BIOLOGY";
			case"a115":	return	"MATERIALS SCIENCE, BIOMATERIALS";
			case"a116":	return	"MATERIALS SCIENCE, CERAMICS";
			case"a117":	return	"MATERIALS SCIENCE, CHARACTERIZATION & TESTI";
			case"a118":	return	"MATERIALS SCIENCE, COATINGS & FILMS";
			case"a119":	return	"MATERIALS SCIENCE, COMPOSITES";
			case"a120":	return	"MATERIALS SCIENCE, MULTIDISCIPLINARY";
			case"a121":	return	"MATERIALS SCIENCE, PAPER & WOOD";
			case"a122":	return	"MATERIALS SCIENCE, TEXTILES";
			case"a123":	return	"MATHEMATICAL & COMPUTATIONAL BIOLOGY";
			case"a124":	return	"MATHEMATICS";
			case"a125":	return	"MATHEMATICS, APPLIED";
			case"a126":	return	"MATHEMATICS, INTERDISCIPLINARY APPLICATIONS";
			case"a127":	return	"MECHANICS";
			case"a128":	return	"MEDICAL ETHICS";
			case"a129":	return	"MEDICAL INFORMATICS";
			case"a130":	return	"MEDICAL LABORATORY TECHNOLOGY";
			case"a131":	return	"MEDICINE, GENERAL & INTERNAL";
			case"a132":	return	"MEDICINE, LEGAL";
			case"a133":	return	"MEDICINE, RESEARCH & EXPERIMENTAL";
			case"a134":	return	"METALLURGY & METALLURGICAL ENGINEERING";
			case"a135":	return	"METEOROLOGY & ATMOSPHERIC SCIENCES";
			case"a136":	return	"MICROBIOLOGY";
			case"a137":	return	"MICROSCOPY";
			case"a138":	return	"MINERALOGY";
			case"a139":	return	"MINING & MINERAL PROCESSING";
			case"a140":	return	"MULTIDISCIPLINARY SCIENCES";
			case"a141":	return	"MYCOLOGY";
			case"a142":	return	"NANOSCIENCE & NANOTECHNOLOGY";
			case"a143":	return	"NEUROIMAGING";
			case"a144":	return	"NEUROSCIENCES";
			case"a145":	return	"NUCLEAR SCIENCE & TECHNOLOGY";
			case"a146":	return	"NURSING";
			case"a147":	return	"NUTRITION & DIETETICS";
			case"a148":	return	"OBSTETRICS & GYNECOLOGY";
			case"a149":	return	"OCEANOGRAPHY";
			case"a150":	return	"ONCOLOGY";
			case"a151":	return	"OPERATIONS RESEARCH & MANAGEMENT SCIENCE";
			case"a152":	return	"OPHTHALMOLOGY";
			case"a153":	return	"OPTICS";
			case"a154":	return	"ORNITHOLOGY";
			case"a155":	return	"ORTHOPEDICS";
			case"a156":	return	"OTORHINOLARYNGOLOGY";
			case"a157":	return	"PALEONTOLOGY";
			case"a158":	return	"PARASITOLOGY";
			case"a159":	return	"PATHOLOGY";
			case"a160":	return	"PEDIATRICS";
			case"a161":	return	"PERIPHERAL VASCULAR DISEASE";
			case"a162":	return	"PHARMACOLOGY & PHARMACY";
			case"a163":	return	"PHYSICS, APPLIED";
			case"a164":	return	"PHYSICS, ATOMIC, MOLECULAR & CHEMICAL";
			case"a165":	return	"PHYSICS, CONDENSED MATTER";
			case"a166":	return	"PHYSICS, FLUIDS & PLASMAS";
			case"a167":	return	"PHYSICS, MATHEMATICAL";
			case"a168":	return	"PHYSICS, MULTIDISCIPLINARY";
			case"a169":	return	"PHYSICS, NUCLEAR";
			case"a170":	return	"PHYSICS, PARTICLES & FIELDS";
			case"a171":	return	"PHYSIOLOGY";
			case"a172":	return	"PLANNING & DEVELOPMENT";
			case"a173":	return	"PLANT SCIENCES";
			case"a174":	return	"POLITICAL SCIENCE";
			case"a175":	return	"POLYMER SCIENCE";
			case"a176":	return	"PSYCHIATRY";
			case"a177":	return	"PSYCHOLOGY";
			case"a178":	return	"PSYCHOLOGY, APPLIED";
			case"a179":	return	"PSYCHOLOGY, BIOLOGICAL";
			case"a180":	return	"PSYCHOLOGY, CLINICAL";
			case"a181":	return	"PSYCHOLOGY, DEVELOPMENTAL";
			case"a182":	return	"PSYCHOLOGY, EDUCATIONAL";
			case"a183":	return	"PSYCHOLOGY, EXPERIMENTAL";
			case"a184":	return	"PSYCHOLOGY, MATHEMATICAL";
			case"a185":	return	"PSYCHOLOGY, MULTIDISCIPLINARY";
			case"a186":	return	"PSYCHOLOGY, PSYCHOANALYSIS";
			case"a187":	return	"PSYCHOLOGY, SOCIAL";
			case"a188":	return	"PUBLIC ADMINISTRATION";
			case"a189":	return	"PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH";
			case"a190":	return	"RADIOLOGY, NUCLEAR MEDICINE & MEDICAL IMAGI";
			case"a191":	return	"REHABILITATION";
			case"a192":	return	"REMOTE SENSING";
			case"a193":	return	"REPRODUCTIVE BIOLOGY";
			case"a194":	return	"RESPIRATORY SYSTEM";
			case"a195":	return	"RHEUMATOLOGY";
			case"a196":	return	"ROBOTICS";
			case"a197":	return	"SOCIAL ISSUES";
			case"a198":	return	"SOCIAL SCIENCES, BIOMEDICAL";
			case"a199":	return	"SOCIAL SCIENCES, INTERDISCIPLINARY";
			case"a200":	return	"SOCIAL SCIENCES, MATHEMATICAL METHODS";
			case"a201":	return	"SOCIAL WORK";
			case"a202":	return	"SOCIOLOGY";
			case"a203":	return	"SOIL SCIENCE";
			case"a204":	return	"SPECTROSCOPY";
			case"a205":	return	"SPORT SCIENCES";
			case"a206":	return	"STATISTICS & PROBABILITY";
			case"a207":	return	"SUBSTANCE ABUSE";
			case"a208":	return	"SURGERY";
			case"a209":	return	"TELECOMMUNICATIONS";
			case"a210":	return	"THERMODYNAMICS";
			case"a211":	return	"TOXICOLOGY";
			case"a212":	return	"TRANSPLANTATION";
			case"a213":	return	"TRANSPORTATION";
			case"a214":	return	"TRANSPORTATION SCIENCE & TECHNOLOGY";
			case"a215":	return	"TROPICAL MEDICINE";
			case"a216":	return	"URBAN STUDIES";
			case"a217":	return	"UROLOGY & NEPHROLOGY";
			case"a218":	return	"VETERINARY SCIENCES";
			case"a219":	return	"VIROLOGY";
			case"a220":	return	"WATER RESOURCES";
			case"a221":	return	"WOMEN'S STUDIES";
			case"a222":	return	"ZOOLOGY";
			default:
				return "UNKNOWN";

			}
			
		}

	public static String getReverseColumnName(String a)
	{
		switch(a)
		{

				case"ACOUSTICS":	return	"a1";
				case"AGRICULTURAL ECONOMICS & POLICY":	return	"a2";
				case"AGRICULTURAL ENGINEERING":	return	"a3";
				case"AGRICULTURE, DAIRY & ANIMAL SCIENCE":	return	"a4";
				case"AGRICULTURE, MULTIDISCIPLINARY":	return	"a5";
				case"AGRONOMY":	return	"a6";
				case"ALLERGY":	return	"a7";
				case"ANATOMY & MORPHOLOGY":	return	"a8";
				case"ANDROLOGY":	return	"a9";
				case"ANESTHESIOLOGY":	return	"a10";
				case"ANTHROPOLOGY":	return	"a11";
				case"AREA STUDIES":	return	"a12";
				case"ASTRONOMY & ASTROPHYSICS":	return	"a13";
				case"AUTOMATION & CONTROL SYSTEMS":	return	"a14";
				case"BEHAVIORAL SCIENCES":	return	"a15";
				case"BIOCHEMICAL RESEARCH METHODS":	return	"a16";
				case"BIOCHEMISTRY & MOLECULAR BIOLOGY":	return	"a17";
				case"BIODIVERSITY CONSERVATION":	return	"a18";
				case"BIOLOGY":	return	"a19";
				case"BIOPHYSICS":	return	"a20";
				case"BIOTECHNOLOGY & APPLIED MICROBIOLOGY":	return	"a21";
				case"BUSINESS":	return	"a22";
				case"BUSINESS, FINANCE":	return	"a23";
				case"CARDIAC & CARDIOVASCULAR SYSTEMS":	return	"a24";
				case"CELL & TISSUE ENGINEERING":	return	"a25";
				case"CELL BIOLOGY":	return	"a26";
				case"CHEMISTRY, ANALYTICAL":	return	"a27";
				case"CHEMISTRY, APPLIED":	return	"a28";
				case"CHEMISTRY, INORGANIC & NUCLEAR":	return	"a29";
				case"CHEMISTRY, MEDICINAL":	return	"a30";
				case"CHEMISTRY, MULTIDISCIPLINARY":	return	"a31";
				case"CHEMISTRY, ORGANIC":	return	"a32";
				case"CHEMISTRY, PHYSICAL":	return	"a33";
				case"CLINICAL NEUROLOGY":	return	"a34";
				case"COMMUNICATION":	return	"a35";
				case"COMPUTER SCIENCE, ARTIFICIAL INTELLIGENCE":	return	"a36";
				case"COMPUTER SCIENCE, CYBERNETICS":	return	"a37";
				case"COMPUTER SCIENCE, HARDWARE & ARCHITECTURE":	return	"a38";
				case"COMPUTER SCIENCE, INFORMATION SYSTEMS":	return	"a39";
				case"COMPUTER SCIENCE, INTERDISCIPLINARY APPLICATIONS":	return	"a40";
				case"COMPUTER SCIENCE, SOFTWARE ENGINEERING":	return	"a41";
				case"COMPUTER SCIENCE, THEORY & METHODS":	return	"a42";
				case"CONSTRUCTION & BUILDING TECHNOLOGY":	return	"a43";
				case"CRIMINOLOGY & PENOLOGY":	return	"a44";
				case"CRITICAL CARE MEDICINE":	return	"a45";
				case"CRYSTALLOGRAPHY":	return	"a46";
				case"DEMOGRAPHY":	return	"a47";
				case"DENTISTRY, ORAL SURGERY & MEDICINE":	return	"a48";
				case"DERMATOLOGY":	return	"a49";
				case"DEVELOPMENTAL BIOLOGY":	return	"a50";
				case"ECOLOGY":	return	"a51";
				case"ECONOMICS":	return	"a52";
				case"EDUCATION & EDUCATIONAL RESEARCH":	return	"a53";
				case"EDUCATION, SCIENTIFIC DISCIPLINES":	return	"a54";
				case"EDUCATION, SPECIAL":	return	"a55";
				case"ELECTROCHEMISTRY":	return	"a56";
				case"EMERGENCY MEDICINE":	return	"a57";
				case"ENDOCRINOLOGY & METABOLISM":	return	"a58";
				case"ENERGY & FUELS":	return	"a59";
				case"ENGINEERING, AEROSPACE":	return	"a60";
				case"ENGINEERING, BIOMEDICAL":	return	"a61";
				case"ENGINEERING, CHEMICAL":	return	"a62";
				case"ENGINEERING, CIVIL":	return	"a63";
				case"ENGINEERING, ELECTRICAL & ELECTRONIC":	return	"a64";
				case"ENGINEERING, ENVIRONMENTAL":	return	"a65";
				case"ENGINEERING, GEOLOGICAL":	return	"a66";
				case"ENGINEERING, INDUSTRIAL":	return	"a67";
				case"ENGINEERING, MANUFACTURING":	return	"a68";
				case"ENGINEERING, MARINE":	return	"a69";
				case"ENGINEERING, MECHANICAL":	return	"a70";
				case"ENGINEERING, MULTIDISCIPLINARY":	return	"a71";
				case"ENGINEERING, OCEAN":	return	"a72";
				case"ENGINEERING, PETROLEUM":	return	"a73";
				case"ENTOMOLOGY":	return	"a74";
				case"ENVIRONMENTAL SCIENCES":	return	"a75";
				case"ENVIRONMENTAL STUDIES":	return	"a76";
				case"ERGONOMICS":	return	"a77";
				case"ETHICS":	return	"a78";
				case"ETHNIC STUDIES":	return	"a79";
				case"EVOLUTIONARY BIOLOGY":	return	"a80";
				case"FAMILY STUDIES":	return	"a81";
				case"FISHERIES":	return	"a82";
				case"FOOD SCIENCE & TECHNOLOGY":	return	"a83";
				case"FORESTRY":	return	"a84";
				case"GASTROENTEROLOGY & HEPATOLOGY":	return	"a85";
				case"GENETICS & HEREDITY":	return	"a86";
				case"GEOCHEMISTRY & GEOPHYSICS":	return	"a87";
				case"GEOGRAPHY":	return	"a88";
				case"GEOGRAPHY, PHYSICAL":	return	"a89";
				case"GEOLOGY":	return	"a90";
				case"GEOSCIENCES, MULTIDISCIPLINARY":	return	"a91";
				case"GERIATRICS & GERONTOLOGY":	return	"a92";
				case"GERONTOLOGY":	return	"a93";
				case"HEALTH CARE SCIENCES & SERVICES":	return	"a94";
				case"HEALTH POLICY & SERVICES":	return	"a95";
				case"HEMATOLOGY":	return	"a96";
				case"HISTORY":	return	"a97";
				case"HISTORY & PHILOSOPHY OF SCIENCE":	return	"a98";
				case"HISTORY OF SOCIAL SCIENCES":	return	"a99";
				case"HORTICULTURE":	return	"a100";
				case"HOSPITALITY, LEISURE, SPORT & TOURISM":	return	"a101";
				case"IMAGING SCIENCE & PHOTOGRAPHIC TECHNOLOGY":	return	"a102";
				case"IMMUNOLOGY":	return	"a103";
				case"INDUSTRIAL RELATIONS & LABOR":	return	"a104";
				case"INFECTIOUS DISEASES":	return	"a105";
				case"INFORMATION SCIENCE & LIBRARY SCIENCE":	return	"a106";
				case"INSTRUMENTS & INSTRUMENTATION":	return	"a107";
				case"INTEGRATIVE & COMPLEMENTARY MEDICINE":	return	"a108";
				case"INTERNATIONAL RELATIONS":	return	"a109";
				case"LAW":	return	"a110";
				case"LIMNOLOGY":	return	"a111";
				case"LINGUISTICS":	return	"a112";
				case"MANAGEMENT":	return	"a113";
				case"MARINE & FRESHWATER BIOLOGY":	return	"a114";
				case"MATERIALS SCIENCE, BIOMATERIALS":	return	"a115";
				case"MATERIALS SCIENCE, CERAMICS":	return	"a116";
				case"MATERIALS SCIENCE, CHARACTERIZATION & TESTI":	return	"a117";
				case"MATERIALS SCIENCE, COATINGS & FILMS":	return	"a118";
				case"MATERIALS SCIENCE, COMPOSITES":	return	"a119";
				case"MATERIALS SCIENCE, MULTIDISCIPLINARY":	return	"a120";
				case"MATERIALS SCIENCE, PAPER & WOOD":	return	"a121";
				case"MATERIALS SCIENCE, TEXTILES":	return	"a122";
				case"MATHEMATICAL & COMPUTATIONAL BIOLOGY":	return	"a123";
				case"MATHEMATICS":	return	"a124";
				case"MATHEMATICS, APPLIED":	return	"a125";
				case"MATHEMATICS, INTERDISCIPLINARY APPLICATIONS":	return	"a126";
				case"MECHANICS":	return	"a127";
				case"MEDICAL ETHICS":	return	"a128";
				case"MEDICAL INFORMATICS":	return	"a129";
				case"MEDICAL LABORATORY TECHNOLOGY":	return	"a130";
				case"MEDICINE, GENERAL & INTERNAL":	return	"a131";
				case"MEDICINE, LEGAL":	return	"a132";
				case"MEDICINE, RESEARCH & EXPERIMENTAL":	return	"a133";
				case"METALLURGY & METALLURGICAL ENGINEERING":	return	"a134";
				case"METEOROLOGY & ATMOSPHERIC SCIENCES":	return	"a135";
				case"MICROBIOLOGY":	return	"a136";
				case"MICROSCOPY":	return	"a137";
				case"MINERALOGY":	return	"a138";
				case"MINING & MINERAL PROCESSING":	return	"a139";
				case"MULTIDISCIPLINARY SCIENCES":	return	"a140";
				case"MYCOLOGY":	return	"a141";
				case"NANOSCIENCE & NANOTECHNOLOGY":	return	"a142";
				case"NEUROIMAGING":	return	"a143";
				case"NEUROSCIENCES":	return	"a144";
				case"NUCLEAR SCIENCE & TECHNOLOGY":	return	"a145";
				case"NURSING":	return	"a146";
				case"NUTRITION & DIETETICS":	return	"a147";
				case"OBSTETRICS & GYNECOLOGY":	return	"a148";
				case"OCEANOGRAPHY":	return	"a149";
				case"ONCOLOGY":	return	"a150";
				case"OPERATIONS RESEARCH & MANAGEMENT SCIENCE":	return	"a151";
				case"OPHTHALMOLOGY":	return	"a152";
				case"OPTICS":	return	"a153";
				case"ORNITHOLOGY":	return	"a154";
				case"ORTHOPEDICS":	return	"a155";
				case"OTORHINOLARYNGOLOGY":	return	"a156";
				case"PALEONTOLOGY":	return	"a157";
				case"PARASITOLOGY":	return	"a158";
				case"PATHOLOGY":	return	"a159";
				case"PEDIATRICS":	return	"a160";
				case"PERIPHERAL VASCULAR DISEASE":	return	"a161";
				case"PHARMACOLOGY & PHARMACY":	return	"a162";
				case"PHYSICS, APPLIED":	return	"a163";
				case"PHYSICS, ATOMIC, MOLECULAR & CHEMICAL":	return	"a164";
				case"PHYSICS, CONDENSED MATTER":	return	"a165";
				case"PHYSICS, FLUIDS & PLASMAS":	return	"a166";
				case"PHYSICS, MATHEMATICAL":	return	"a167";
				case"PHYSICS, MULTIDISCIPLINARY":	return	"a168";
				case"PHYSICS, NUCLEAR":	return	"a169";
				case"PHYSICS, PARTICLES & FIELDS":	return	"a170";
				case"PHYSIOLOGY":	return	"a171";
				case"PLANNING & DEVELOPMENT":	return	"a172";
				case"PLANT SCIENCES":	return	"a173";
				case"POLITICAL SCIENCE":	return	"a174";
				case"POLYMER SCIENCE":	return	"a175";
				case"PSYCHIATRY":	return	"a176";
				case"PSYCHOLOGY":	return	"a177";
				case"PSYCHOLOGY, APPLIED":	return	"a178";
				case"PSYCHOLOGY, BIOLOGICAL":	return	"a179";
				case"PSYCHOLOGY, CLINICAL":	return	"a180";
				case"PSYCHOLOGY, DEVELOPMENTAL":	return	"a181";
				case"PSYCHOLOGY, EDUCATIONAL":	return	"a182";
				case"PSYCHOLOGY, EXPERIMENTAL":	return	"a183";
				case"PSYCHOLOGY, MATHEMATICAL":	return	"a184";
				case"PSYCHOLOGY, MULTIDISCIPLINARY":	return	"a185";
				case"PSYCHOLOGY, PSYCHOANALYSIS":	return	"a186";
				case"PSYCHOLOGY, SOCIAL":	return	"a187";
				case"PUBLIC ADMINISTRATION":	return	"a188";
				case"PUBLIC, ENVIRONMENTAL & OCCUPATIONAL HEALTH":	return	"a189";
				case"RADIOLOGY, NUCLEAR MEDICINE & MEDICAL IMAGI":	return	"a190";
				case"REHABILITATION":	return	"a191";
				case"REMOTE SENSING":	return	"a192";
				case"REPRODUCTIVE BIOLOGY":	return	"a193";
				case"RESPIRATORY SYSTEM":	return	"a194";
				case"RHEUMATOLOGY":	return	"a195";
				case"ROBOTICS":	return	"a196";
				case"SOCIAL ISSUES":	return	"a197";
				case"SOCIAL SCIENCES, BIOMEDICAL":	return	"a198";
				case"SOCIAL SCIENCES, INTERDISCIPLINARY":	return	"a199";
				case"SOCIAL SCIENCES, MATHEMATICAL METHODS":	return	"a200";
				case"SOCIAL WORK":	return	"a201";
				case"SOCIOLOGY":	return	"a202";
				case"SOIL SCIENCE":	return	"a203";
				case"SPECTROSCOPY":	return	"a204";
				case"SPORT SCIENCES":	return	"a205";
				case"STATISTICS & PROBABILITY":	return	"a206";
				case"SUBSTANCE ABUSE":	return	"a207";
				case"SURGERY":	return	"a208";
				case"TELECOMMUNICATIONS":	return	"a209";
				case"THERMODYNAMICS":	return	"a210";
				case"TOXICOLOGY":	return	"a211";
				case"TRANSPLANTATION":	return	"a212";
				case"TRANSPORTATION":	return	"a213";
				case"TRANSPORTATION SCIENCE & TECHNOLOGY":	return	"a214";
				case"TROPICAL MEDICINE":	return	"a215";
				case"URBAN STUDIES":	return	"a216";
				case"UROLOGY & NEPHROLOGY":	return	"a217";
				case"VETERINARY SCIENCES":	return	"a218";
				case"VIROLOGY":	return	"a219";
				case"WATER RESOURCES":	return	"a220";
				case"WOMEN'S STUDIES":	return	"a221";
				case"ZOOLOGY":	return	"a222";
				default:
					return "UNKNOWN";
		}
		
	}
}
